language: python
cache: pip
dist: xenial
python:
- '2.7'
- '3.6'
env:
- SALT=2019.2
- SALT=2018.3
- SALT=2017.7
- SALT=2016.11
install:
- pip install tox-travis
script:
- tox
matrix:
  exclude:
  - python: '3.6'
    env: SALT=2016.11
